### PR TITLE
sdl mac

### PR DESCRIPTION
**Pull request by xyl1t**
- added `USE_GPM` directives to use the gpm lib if available 
- replaced some headers to work for mac
- added makefiles that will be used to compile on mac (they are literally the same as the other makefiles except for some compiler and linker flags)
- added alternative middle mouse button: alt + right mouse button
- fixed small bug in asciiid where clipping was too aggressive 
- replaced most of `#ifdef __linux__` to `#if defined(__linux__) || defined(__APPLE__)`

The separate makefiles for mac are sub optimal, could be done better.
Sorry that the PR took so long.

### CODE REVIEW

**Comment by XTeamXeno** [comment]
doesn't this conflict with asciiid.cpp?

**Comment by xyl1t** [comment]
those were minor conflicts, but after 3 tries it's all good now

**Comment by msokalski** [comment]
Hey, any chance you could fix current master branch so it runs on a mac?

**Comment by msokalski** [comment]
superseded by another PR (already merged)

**Pull request closed without merging**
